site_name: Tampere University ITC Wiki

theme:
    name:
        material
    palette:
        primary:
            deep purple
    logo:
        assets/logo.png
    favicon:
        assets/favicon.ico

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.details
